# Generated by Django 4.2.4 on 2023-11-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "award_photo",
                    models.ImageField(
                        max_length=255, upload_to="award_photo", verbose_name="獎項圖片"
                    ),
                ),
                (
                    "big_title",
                    models.CharField(max_length=50, null=True, verbose_name="大標題"),
                ),
                (
                    "small_title",
                    models.CharField(max_length=50, null=True, verbose_name="小標題"),
                ),
                (
                    "modify_date",
                    models.DateTimeField(auto_now=True, verbose_name="修改日期"),
                ),
                ("create_date", models.DateField(auto_now=True, verbose_name="建立日期")),
            ],
            options={
                "verbose_name_plural": "獲得獎項列表",
                "db_table": "award",
            },
        ),
    ]
