# Generated by Django 4.2.4 on 2023-11-07 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="article_category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_category",
                    models.CharField(max_length=10, verbose_name="文章類別"),
                ),
            ],
            options={
                "verbose_name_plural": "文章類別",
                "db_table": "article_category",
            },
        ),
        migrations.CreateModel(
            name="BlogBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banner_photo",
                    models.ImageField(
                        max_length=255,
                        upload_to="BlogBannerPhoto",
                        verbose_name="文章Banner圖",
                    ),
                ),
                (
                    "modify_date",
                    models.DateTimeField(auto_now=True, verbose_name="修改時間"),
                ),
                (
                    "create_date",
                    models.DateField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name_plural": "文章Banner圖片",
                "db_table": "blog_banner",
            },
        ),
        migrations.CreateModel(
            name="article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="標題")),
                ("small_title", models.CharField(max_length=100, verbose_name="小標題")),
                ("content", models.TextField(blank=True, verbose_name="文案")),
                ("author_name", models.CharField(max_length=10, verbose_name="作者")),
                (
                    "modify_date",
                    models.DateTimeField(auto_now=True, verbose_name="修改時間"),
                ),
                (
                    "create_date",
                    models.DateField(auto_now_add=True, verbose_name="新增時間"),
                ),
                (
                    "article_photo",
                    models.ImageField(
                        max_length=255, upload_to="article_photo", verbose_name="文章圖片"
                    ),
                ),
                (
                    "article_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="blog.article_category",
                        verbose_name="文章類別",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "文章內容",
                "db_table": "article",
            },
        ),
    ]
