# Generated by Django 4.2.4 on 2023-11-03 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DepartmentFormCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=10, verbose_name="部門")),
            ],
            options={
                "verbose_name_plural": "部門",
                "db_table": "department_form_category",
            },
        ),
        migrations.CreateModel(
            name="FormLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_date",
                    models.DateField(auto_created=True, verbose_name="建立日期"),
                ),
                ("from_name", models.CharField(max_length=50, verbose_name="表單名稱")),
                ("modify_date", models.DateField(auto_now=True, verbose_name="修改日期")),
                (
                    "department_form_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fastlink.departmentformcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "表單",
                "db_table": "formlink",
            },
        ),
    ]
