# Generated by Django 4.2.4 on 2023-11-03 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("fastlink", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formlink",
            name="form_link",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=255, verbose_name="表單連結"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="formlink",
            name="create_date",
            field=models.DateField(auto_now=True, verbose_name="建立日期"),
        ),
    ]
