# Generated by Django 4.2.4 on 2023-11-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fastlink", "0003_fastlinkbanner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="common_link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_title", models.CharField(max_length=50, verbose_name="常用連結名稱")),
                ("link_href", models.CharField(max_length=100, verbose_name="使用連結或說明")),
                (
                    "modify_date",
                    models.DateTimeField(auto_now=True, verbose_name="修改時間"),
                ),
                (
                    "create_date",
                    models.DateField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name_plural": "常用連結",
                "db_table": "common_link",
            },
        ),
        migrations.AddField(
            model_name="formlink",
            name="modify_user",
            field=models.CharField(max_length=50, null=True, verbose_name="修改者"),
        ),
    ]
