# Generated by Django 4.2.4 on 2023-11-07 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fastlink", "0004_common_link_formlink_modify_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formlink",
            old_name="from_name",
            new_name="form_name",
        ),
    ]
