# Generated by Django 4.2.4 on 2023-10-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutIntroduce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_line", models.CharField(max_length=10, verbose_name="第一段字")),
                ("second_line", models.CharField(max_length=20, verbose_name="第二段字")),
                ("third_line", models.CharField(max_length=255, verbose_name="第三段字")),
                (
                    "modify_date",
                    models.DateTimeField(auto_now=True, verbose_name="修改時間"),
                ),
                (
                    "create_date",
                    models.DateField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name_plural": "關於介紹文字",
                "db_table": "about_introduce",
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="精神喊話")),
                ("name", models.CharField(max_length=20, verbose_name="名字")),
                ("position", models.CharField(max_length=10, verbose_name="職稱")),
            ],
            options={
                "verbose_name_plural": "主管的精神喊話",
                "db_table": "quote",
            },
        ),
    ]
