# Generated by Django 4.2.4 on 2023-10-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeBanner1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banner_photo",
                    models.ImageField(
                        max_length=255, upload_to="HomeBannerPhoto1", verbose_name="圖片"
                    ),
                ),
                (
                    "modify_date",
                    models.DateTimeField(auto_now=True, verbose_name="修改時間"),
                ),
                (
                    "create_date",
                    models.DateField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name_plural": "首頁第一區塊圖片",
                "db_table": "home_banner_first",
            },
        ),
        migrations.CreateModel(
            name="HomeBanner2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banner_photo",
                    models.ImageField(
                        max_length=255, upload_to="HomeBannerPhoto2", verbose_name="圖片"
                    ),
                ),
                (
                    "modify_date",
                    models.DateTimeField(auto_now=True, verbose_name="修改時間"),
                ),
                (
                    "create_date",
                    models.DateField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name_plural": "首頁第二區塊圖片",
                "db_table": "home_banner_second",
            },
        ),
        migrations.CreateModel(
            name="HomeBanner3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banner_photo",
                    models.ImageField(
                        max_length=255, upload_to="HomeBannerPhoto3", verbose_name="圖片"
                    ),
                ),
                (
                    "modify_date",
                    models.DateTimeField(auto_now=True, verbose_name="修改時間"),
                ),
                (
                    "create_date",
                    models.DateField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name_plural": "首頁第三區塊圖片",
                "db_table": "home_banner_third",
            },
        ),
        migrations.CreateModel(
            name="HomeBanner4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banner_photo",
                    models.ImageField(
                        max_length=255, upload_to="HomeBannerPhoto4", verbose_name="圖片"
                    ),
                ),
                (
                    "modify_date",
                    models.DateTimeField(auto_now=True, verbose_name="修改時間"),
                ),
                (
                    "create_date",
                    models.DateField(auto_now_add=True, verbose_name="建立時間"),
                ),
            ],
            options={
                "verbose_name_plural": "首頁第四區塊圖片",
                "db_table": "home_banner_fourth",
            },
        ),
        migrations.CreateModel(
            name="RunHorseLight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_or_not", models.BooleanField(verbose_name="是否要顯示")),
                ("announcement", models.CharField(max_length=100, verbose_name="公告文字")),
                (
                    "modify_date",
                    models.DateTimeField(auto_now=True, verbose_name="修改時間"),
                ),
                ("modify_user", models.CharField(max_length=50, verbose_name="修改者")),
            ],
            options={
                "verbose_name_plural": "跑馬燈",
                "db_table": "marquee",
            },
        ),
    ]
