# Generated by Django 4.2.4 on 2023-10-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0002_alter_homebanner1_banner_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homebanner1",
            name="banner_photo",
            field=models.ImageField(max_length=255, upload_to="HomeBannerPhoto1"),
        ),
    ]
